export const sheetData = [
    {
        tab: "AIR",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Deaths from air pollution",
        selector: "deaths_from_air_pollution",
        Label: "air",
    },
    {
        tab: "AIR",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Deaths from indoor air pollution",
        selector: "deaths_from_indoor_air_pollution",
        Label: "air",
    },
    {
        tab: "AIR",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Liters of Air that you have inhaled",
        selector: "liters_of_air_that_you_have_inhaled",
        Label: "air",
    },
    {
        tab: "AIR",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Time left to recovery of ozone hole",
        selector: "time_left_to_recovery_of_the_ozone_hole",
        Label: "air",
    },
    {
        tab: "AIR",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Years of healthy life lost from air pollution",
        selector: "years_of_healthy_life_lost_from_air_pollution",
        Label: "air",
    },
    {
        tab: "CLOTHING & OTHER PRODUCTS",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Car Produced",
        selector: "cars_produced",
        Label: "challenges",
    },
    {
        tab: "CHEMICALS",
        sheet: "PHC - TOXIC EXPOSURE",
        id: "18fpaw9LlMkzeKktCfdApuGj-kzNtmr0UWkJx0oVUrqM",
        value: "Tons of Bisphenol A Produced",
        selector: "tons_of_bisphenol_a_produced",
        Label: "chemicals",
    },
    {
        tab: "CHEMICALS",
        sheet: "PHC - TOXIC EXPOSURE",
        id: "18fpaw9LlMkzeKktCfdApuGj-kzNtmr0UWkJx0oVUrqM",
        value: "Tons of Pesticide Used",
        selector: "tons_of_pesticides_used",
        Label: "chemicals",
    },
    {
        tab: "CHEMICALS",
        sheet: "PHC - TOXIC EXPOSURE",
        id: "18fpaw9LlMkzeKktCfdApuGj-kzNtmr0UWkJx0oVUrqM",
        value: "Tons of Phthalates Produced",
        selector: "tons_of_phthalates_produced",
        Label: "chemicals",
    },
    {
        tab: "PLASTIC & ALUMINUM CANS",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Tons of PVC Plastic Produced",
        selector: "tons_of_pvc_plastics_produced",
        Label: "chemicals",
    },
    {
        tab: "CLOTHING & OTHER PRODUCTS",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Tons of Cotton Produced",
        selector: "tons_of_cotton_produced",
        Label: "clothing",
    },
    {
        tab: "CLOTHING & OTHER PRODUCTS",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Tons of Organic Cotton Produced",
        selector: "tons_of_organic_cotton_produced",
        Label: "clothing",
    },
    {
        tab: "CLOTHING & OTHER PRODUCTS",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Tons of Paper Produced",
        selector: "tons_of_paper_produced",
        Label: "clothing",
    },
    {
        tab: "CLOTHING & OTHER PRODUCTS",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Tons of Water Used in Cotton Production",
        selector: "tons_of_water_used_in_cotton_production",
        Label: "clothing",
    },
    {
        tab: "CLOTHING & OTHER PRODUCTS",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "US Dollars Spent on Cotton Pesticides",
        selector: "us_dollars_spent_on_cotton_pesticides",
        Label: "clothing",
    },
    {
        tab: "ENERGY CONSUMPTION",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Terajoules of Electricity Used",
        selector: "terajoules_of_electricity_used",
        Label: "energy",
    },
    {
        tab: "ENERGY CONSUMPTION",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Terajoules of Energy Used",
        selector: "terajoules_of_energy_used",
        Label: "energy",
    },
    {
        tab: "RENEWABLE",
        sheet: "PHC - ENERGY",
        id: "1gQguJ7qDjiazv-RWKp8KX7H7YjFnwBiHCUxa-zb-Gfw",
        value: "Percent of Electricity Produced from Renewable Sources",
        selector: "percent_of_electricity_produced_from_renewable_sources",
        Label: "energy",
    },
    {
        tab: "RENEWABLE",
        sheet: "PHC - ENERGY",
        id: "1gQguJ7qDjiazv-RWKp8KX7H7YjFnwBiHCUxa-zb-Gfw",
        value: "Terajoules of Electricity Used",
        selector: "terajoules_of_electricity_used",
        Label: "energy",
    },
    {
        tab: "RENEWABLE",
        sheet: "PHC - ENERGY",
        id: "1gQguJ7qDjiazv-RWKp8KX7H7YjFnwBiHCUxa-zb-Gfw",
        value: "Terajoules of Solar Energy Striking Earth",
        selector: "terajoules_of_solar_energy_striking_earth",
        Label: "energy",
    },
    {
        tab: "CHEMICALS",
        sheet: "PHC - TOXIC EXPOSURE",
        id: "18fpaw9LlMkzeKktCfdApuGj-kzNtmr0UWkJx0oVUrqM",
        value: "Tons of Antibiotics Used for Livestock",
        selector: "tons_of_antibiotics_used_for_livestock",
        Label: "foods",
    },
    {
        tab: "FOOD & BEVERAGE",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Tons of Chocolate Eaten",
        selector: "tons_of_chocolate_eaten",
        Label: "foods",
    },
    {
        tab: "FOOD & BEVERAGE",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Tons of Food Lost or Wasted",
        selector: "tons_of_food_lost_or_wasted",
        Label: "foods",
    },
    {
        tab: "FOOD & BEVERAGE",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Tons of Meat Eaten",
        selector: "tons_of_meat_eaten",
        Label: "foods",
    },
    {
        tab: "FOOD & BEVERAGE",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Tons of Water Used in Meat Production",
        selector: "tons_of_water_used_in_meat_production",
        Label: "foods",
    },
    {
        tab: "FOOD & BEVERAGE",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "US Dollars Spent on Organic Products",
        selector: "us_dollars_spent_on_organic_food",
        Label: "foods",
    },
    {
        tab: "PLASTIC & ALUMINUM CANS",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Aluminum Cans Consumed",
        selector: "aluminium_cans_consumed",
        Label: "foods",
    },
    {
        tab: "PLASTIC & ALUMINUM CANS",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Recycled Aluminum",
        selector: "recycled_aluminium",
        Label: "foods",
    },
    {
        tab: "FOREST & DESERTIFICATION",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Cubic Meters of Wood Produced",
        selector: "cubic_meters_of_wood_produced",
        Label: "forests",
    },
    {
        tab: "FOREST & DESERTIFICATION",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Cubic Metres of Roundwood from Responsibly Managed Forests",
        selector: "cubic_metres_of_roundwood_from_responsibly_managed_forests",
        Label: "forests",
    },
    {
        tab: "FOREST & DESERTIFICATION",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Hectares of Forests Cut Down or Burned",
        selector: "hectares_of_forests_cut_down_or_burned",
        Label: "forests",
    },
    {
        tab: "FOREST & DESERTIFICATION",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Hectares of Replanted Forests",
        selector: "hectares_of_replanted_forests",
        Label: "forests",
    },
    {
        tab: "FOREST & DESERTIFICATION",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Percent of Species in Critical Risk of Extinction",
        selector: "percent_of_species_in_critical_risk_of_extinction",
        Label: "forests",
    },
    {
        tab: "FOREST & DESERTIFICATION",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Percent of Wild Forest Left",
        selector: "percent_of_wild_forests_left",
        Label: "forests",
    },
    {
        tab: "FOREST & DESERTIFICATION",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Squared Kilometers of Land Area Being Degraded",
        selector: "square_kilometers_of_land_area_being_degraded",
        Label: "forests",
    },
    {
        tab: "FOOD & BEVERAGE",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Tons of Virtual Water Traded",
        selector: "tons_of_virtual_water_traded",
        Label: "freshwater",
    },
    {
        tab: "FOOD & BEVERAGE",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Tons of Fresh Water Used",
        selector: "tons_of_freshwater_used",
        Label: "freshwater",
    },
    {
        tab: "FOOD & BEVERAGE",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Tons of Water Used for Our Consumption",
        selector: "tons_of_water_used_for_our_consumption",
        Label: "freshwater",
    },
    {
        tab: "FRESH WATER",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Deaths from Dirty Water and Related Diseases",
        selector: "deaths_from_dirty_water_and_related_diseases",
        Label: "freshwater",
    },
    {
        tab: "FRESH WATER",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Liters of Water you have Used",
        selector: "liters_of_water_you_have_used",
        Label: "freshwater",
    },
    {
        tab: "FRESH WATER",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Number of People in Need of Water",
        selector: "number_of_people_in_need_of_water",
        Label: "freshwater",
    },
    {
        tab: "FRESH WATER",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of ‘Virtual’ Water Traded",
        selector: "tons_of_virtual_water_traded",
        Label: "freshwater",
    },
    {
        tab: "FRESH WATER",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of Freshwater Used",
        selector: "tons_of_freshwater_used",
        Label: "freshwater",
    },
    {
        tab: "FRESH WATER",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of Groundwater Being Polluted",
        selector: "tons_of_groundwater_being_polluted",
        Label: "freshwater",
    },
    {
        tab: "FRESH WATER",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of Water Used for our Consumption",
        selector: "tons_of_water_used_for_our_consumption",
        Label: "freshwater",
    },
    {
        tab: "AIR",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of co2 emitted into the atmosphere",
        selector: "tons_of_co2_emitted_into_the_atmosphere",
        Label: "global_warming",
    },
    {
        tab: "AIR",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "World average temperature",
        selector: "world_average_temperature",
        Label: "global_warming",
    },
    {
        tab: "OCEAN & SEA",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Rise in the sea level",
        selector: "rise_in_sea_level",
        Label: "global_warming",
    },
    {
        tab: "OCEAN & SEA",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of melted ice",
        selector: "tons_of_melted_ice",
        Label: "global_warming",
    },
    {
        tab: "ENERGY CONSUMPTION",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Energy Used in Mining",
        selector: "energy_use_from_mining",
        Label: "mining",
    },
    {
        tab: "MINING",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Energy Used from Mining",
        selector: "energy_use_from_mining",
        Label: "mining",
    },
    {
        tab: "MINING",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of Coal Mined",
        selector: "tons_of_coal_mined",
        Label: "mining",
    },
    {
        tab: "MINING",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of Gold Mined",
        selector: "tons_of_gold_mined",
        Label: "mining",
    },
    {
        tab: "MINING",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Resources Extracted from Earth",
        selector: "tons_of_resources_mined_from_earth",
        Label: "mining",
    },
    {
        tab: "MINING",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of Steel Produced",
        selector: "tons_of_steel_produced",
        Label: "mining",
    },
    {
        tab: "MINING",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of Steel Recycled",
        selector: "tons_of_steel_recycled",
        Label: "mining",
    },
    {
        tab: "MINING",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of Toxic Waste Produced from Gold Mining",
        selector: "tons_of_toxic_waste_produced_from_gold_mining",
        Label: "mining",
    },
    {
        tab: "MINING",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of Wastewater from Steel Mining",
        selector: "tons_of_wastewater_from_steel_mining",
        Label: "mining",
    },
    {
        tab: "FOOD & BEVERAGE",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Time Left to the End of Seafood(if current trends continue)",
        selector: "time_left_to_the_end_of_seafood",
        Label: "oceans",
    },
    {
        tab: "OCEAN & SEA",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Percent of coral reefs left",
        selector: "percent_coral_reefs_left",
        Label: "oceans",
    },
    {
        tab: "OCEAN & SEA",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Time left to the end of seafood",
        selector: "time_left_to_the_end_of_seafood",
        Label: "oceans",
    },
    {
        tab: "OCEAN & SEA",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Time left till no more fish in the sea",
        selector: "time_left_to_the_end_of_seafood",
        Label: "oceans",
    },
    {
        tab: "OCEAN & SEA",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of discarded fish",
        selector: "tons_of_discarded_fish",
        Label: "oceans",
    },
    {
        tab: "OCEAN & SEA",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of plastic waste dumped in oceans",
        selector: "tons_of_plastic_waste_dumped_in_oceans",
        Label: "oceans",
    },
    {
        tab: "OCEAN & SEA",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Tons of seafood produced",
        selector: "tons_of_seafood_produced",
        Label: "oceans",
    },
    {
        tab: "PLASTIC & ALUMINUM CANS",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Tons of Plastic Waste Dumped in Oceans",
        selector: "tons_of_plastic_waste_dumped_in_oceans",
        Label: "oceans",
    },
    {
        tab: "WASTE",
        sheet: "PHC - TOXIC EXPOSURE",
        id: "18fpaw9LlMkzeKktCfdApuGj-kzNtmr0UWkJx0oVUrqM",
        value: "Tons of Plastic Waste Dumped in Oceans",
        selector: "tons_of_plastic_waste_dumped_in_oceans",
        Label: "oceans",
    },
    {
        tab: "ENERGY CONSUMPTION",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Gigajoules used in households",
        selector: "gigajoules_used_in_households",
        Label: "other",
    },
    {
        tab: "FOOD & BEVERAGE",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Number of Obese People in the World",
        selector: "number_of_obese_people",
        Label: "people",
    },
    {
        tab: "FOOD & BEVERAGE",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Number of People who Died of Hunger",
        selector: "people_who_died_from_hunger",
        Label: "people",
    },
    {
        tab: "FOOD & BEVERAGE",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Earth Running Out of Food(if current trends continue)",
        selector: "earth_running_out_of_food",
        Label: "planet",
    },
    {
        tab: "FOREST & DESERTIFICATION",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Time Left till the End of Rain Forest (if current trends continue)",
        selector: "time_left_till_the_end_of_rainforest",
        Label: "planet",
    },
    {
        tab: "FRESH WATER",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Time Left till the World Runs Out of Fresh Water(if current trends continue)",
        selector: "earth_running_out_of_freshwater",
        Label: "planet",
    },
    {
        tab: "WASTE",
        sheet: "PHC - TOXIC EXPOSURE",
        id: "18fpaw9LlMkzeKktCfdApuGj-kzNtmr0UWkJx0oVUrqM",
        value: "Tons of Solid Waste Generated",
        selector: "tons_of_solid_waste_generated",
        Label: "planet",
    },
    {
        tab: "WASTE",
        sheet: "PHC - TOXIC EXPOSURE",
        id: "18fpaw9LlMkzeKktCfdApuGj-kzNtmr0UWkJx0oVUrqM",
        value: "Tons of Waste Dumped",
        selector: "tons_of_waste_dumped",
        Label: "planet",
    },
    {
        tab: "PLASTIC & ALUMINUM CANS",
        sheet: "PHC - CONSUMPTION",
        id: "1XMV9Qi2p4xWuMOWyK6IGhm-YRacNMDedEOI8HO-DqAM",
        value: "Number of Plastic Bags Produced",
        selector: "number_of_plastic_bags_produced",
        Label: "waste",
    },
    {
        tab: "WASTE",
        sheet: "PHC - TOXIC EXPOSURE",
        id: "18fpaw9LlMkzeKktCfdApuGj-kzNtmr0UWkJx0oVUrqM",
        value: "Great Pacific Garbage Patch",
        selector: "great_pacific_garbage_patch",
        Label: "waste",
    },
    {
        tab: "WASTE",
        sheet: "PHC - TOXIC EXPOSURE",
        id: "18fpaw9LlMkzeKktCfdApuGj-kzNtmr0UWkJx0oVUrqM",
        value: "Tons of Electronic Waste Thrown Out",
        selector: "tons_of_electronic_waste_thrown_out",
        Label: "waste",
    },
    {
        tab: "WASTE",
        sheet: "PHC - TOXIC EXPOSURE",
        id: "18fpaw9LlMkzeKktCfdApuGj-kzNtmr0UWkJx0oVUrqM",
        value: "Tons of Hazardous Waste Produced",
        selector: "tons_of_hazardous_waste_thrown_out",
        Label: "waste",
    },
    {
        tab: "WASTE",
        sheet: "PHC - TOXIC EXPOSURE",
        id: "18fpaw9LlMkzeKktCfdApuGj-kzNtmr0UWkJx0oVUrqM",
        value: "Tons of Hazardous Waste Thrown Out",
        selector: "tons_of_hazardous_waste_thrown_out",
        Label: "waste",
    },
    {
        tab: "WASTE",
        sheet: "PHC - TOXIC EXPOSURE",
        id: "18fpaw9LlMkzeKktCfdApuGj-kzNtmr0UWkJx0oVUrqM",
        value: "Tons of Waste from Households",
        selector: "tons_of_waste_from_households",
        Label: "waste",
    },
    {
        tab: "CHEMICALS",
        sheet: "PHC - TOXIC EXPOSURE",
        id: "18fpaw9LlMkzeKktCfdApuGj-kzNtmr0UWkJx0oVUrqM",
        value: "Toxic Chemical Released in the Environment",
        selector: "toxic_chemical_released_in_the_environment",
        Label: "worldometers",
    },
    {
        tab: "FOREST & DESERTIFICATION",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Desertification",
        selector: "desertification",
        Label: "worldometers",
    },
    {
        tab: "FOREST & DESERTIFICATION",
        sheet: "PHC - ENVIRONMENT",
        id: "1eIRgG-VFcQCtIJ0_gvY0QGQK8HLCqX3Y8AQBYItQ3_U",
        value: "Land Lost to Soil Erosion",
        selector: "land_lost_to_soil_erosion",
        Label: "worldometers",
    },
    {
        tab: "NON-RENEWABLE",
        sheet: "PHC - ENERGY",
        id: "1gQguJ7qDjiazv-RWKp8KX7H7YjFnwBiHCUxa-zb-Gfw",
        value: "Days to the End of Coal (if current trends continue)",
        selector: "days_to_the_end_of_coal",
        Label: "worldometers",
    },
    {
        tab: "NON-RENEWABLE",
        sheet: "PHC - ENERGY",
        id: "1gQguJ7qDjiazv-RWKp8KX7H7YjFnwBiHCUxa-zb-Gfw",
        value: "Coal Left (boe) (if current trends continue)",
        selector: "coal_left_boe",
        Label: "worldometers",
    },
    {
        tab: "NON-RENEWABLE",
        sheet: "PHC - ENERGY",
        id: "1gQguJ7qDjiazv-RWKp8KX7H7YjFnwBiHCUxa-zb-Gfw",
        value: "From Non-Renewable Sources (MWh)",
        selector: "from_non_renewable_sources_mwh",
        Label: "worldometers",
    },
    {
        tab: "NON-RENEWABLE",
        sheet: "PHC - ENERGY",
        id: "1gQguJ7qDjiazv-RWKp8KX7H7YjFnwBiHCUxa-zb-Gfw",
        value: "Days to the End of Natural Gas (if current trends continue)",
        selector: "days_to_the_end_of_natural_gas",
        Label: "worldometers",
    },
    {
        tab: "NON-RENEWABLE",
        sheet: "PHC - ENERGY",
        id: "1gQguJ7qDjiazv-RWKp8KX7H7YjFnwBiHCUxa-zb-Gfw",
        value: "Natural Gas Left (boe) (if current trends continue)",
        selector: "natural_gas_left_boe",
        Label: "worldometers",
    },
    {
        tab: "NON-RENEWABLE",
        sheet: "PHC - ENERGY",
        id: "1gQguJ7qDjiazv-RWKp8KX7H7YjFnwBiHCUxa-zb-Gfw",
        value: "Oil Pumped Today",
        selector: "oil_pumped_today",
        Label: "worldometers",
    },
    {
        tab: "NON-RENEWABLE",
        sheet: "PHC - ENERGY",
        id: "1gQguJ7qDjiazv-RWKp8KX7H7YjFnwBiHCUxa-zb-Gfw",
        value: "Oil Consumption",
        selector: "oil_consumption",
        Label: "worldometers",
    },
    {
        tab: "NON-RENEWABLE",
        sheet: "PHC - ENERGY",
        id: "1gQguJ7qDjiazv-RWKp8KX7H7YjFnwBiHCUxa-zb-Gfw",
        value: "Time Left to the End of Oil (if current trends continue)",
        selector: "oil_left_in_the_world",
        Label: "worldometers",
    },
    {
        tab: "NON-RENEWABLE",
        sheet: "PHC - ENERGY",
        id: "1gQguJ7qDjiazv-RWKp8KX7H7YjFnwBiHCUxa-zb-Gfw",
        value: "Oil Left in the World(if current trends continue)",
        selector: "oil_left_in_the_world",
        Label: "worldometers",
    },
    {
        tab: "RENEWABLE",
        sheet: "PHC - ENERGY",
        id: "1gQguJ7qDjiazv-RWKp8KX7H7YjFnwBiHCUxa-zb-Gfw",
        value: "From Renewable Sources (MWh)",
        selector: "from_renewable_sources_mwh",
        Label: "worldometers",
    },
];
export const tabs = {
    "CLOTHING & OTHER PRODUCTS": {},
    CHEMICALS: {},
    "PLASTIC & ALUMINUM CANS": {},
    "ENERGY CONSUMPTION": {},
    RENEWABLE: {},
    "FOOD & BEVERAGE": {},
    "FOREST & DESERTIFICATION": {},
    "FRESH WATER": {},
    "OCEAN & SEA": {},
    MINING: {},
    WASTE: {},
    "NON-RENEWABLE": {},
    AIR: {},
};
export const selector = {
    worldometers: {
        days_to_the_end_of_coal: `[rel="coal_days"]`,
        coal_left_boe: `[rel="coal_reserves"]`,
        desertification: `[rel="desert_land_formed/this_year"]`,
        from_non_renewable_sources_mwh: `[rel="energy_nonren"]`,
        from_renewable_sources_mwh: `[rel="energy_used/today"]`,
        days_to_the_end_of_natural_gas: `[rel="gas_days"]`,
        natural_gas_left_boe: `[rel="gas_reserves"]`,
        oil_pumped_today: `[rel="oil_consumption"]`,
        oil_consumption: `[rel="oil_consumption"]`,
        oil_left_in_the_world: `[rel="oil_days"]`,
        oil_left_in_the_world: `[rel="oil_reserves"]`,
        land_lost_to_soil_erosion: `[rel="soil_erosion/this_year"]`,
        toxic_chemical_released_in_the_environment: `[rel="tox_chem/this_year"]`,
    },
    waste: {
        great_pacific_garbage_patch: `[data-content*='great_pacific_garbage_patch'] .counter`,
        number_of_plastic_bags_produced: `[data-content*='number_of_plastic_bags_produced'] .counter`,
        tons_of_electronic_waste_thrown_out: `[data-content*='tons_of_electronic_waste_thrown_out'] .counter`,
        tons_of_hazardous_waste_thrown_out: `[data-content*='tons_of_hazardous_waste_thrown_out'] .counter`,
        tons_of_hazardous_waste_thrown_out: `[data-content*='tons_of_hazardous_waste_thrown_out'] .counter`,
        tons_of_waste_from_households: `[data-content*='tons_of_waste_from_households'] .counter`,
    },
    planet: {
        earth_running_out_of_food: `[data-content*='earth_running_out_of_food'] .counter`,
        earth_running_out_of_freshwater: `[data-content*='earth_running_out_of_freshwater'] .counter`,
        time_left_till_the_end_of_rainforest: `[data-content*='time_left_till_the_end_of_rainforest'] .counter`,
        tons_of_solid_waste_generated: `[data-content*='tons_of_solid_waste_generated'] .counter`,
        tons_of_waste_dumped: `[data-content*='tons_of_waste_dumped'] .counter`,
    },
    people: {
        number_of_obese_people: `[data-content*='number_of_obese_people'] .counter`,
        people_who_died_from_hunger: `[data-content*='people_who_died_from_hunger'] .counter`,
    },
    other: {
        tons_of_paper_produced: `[data-content*='tons_of_paper_produced'] .counter`,
        gigajoules_used_in_households: `[data-content*='gigajoules_used_in_households'] .counter`,
    },
    oceans: {
        percent_coral_reefs_left: `[data-content*='percent_coral_reefs_left'] .counter`,
        time_left_to_the_end_of_seafood: `[data-content*='time_left_to_the_end_of_seafood'] .counter`,
        time_left_to_the_end_of_seafood: `[data-content*='time_left_to_the_end_of_seafood'] .counter`,
        time_left_to_the_end_of_seafood: `[data-content*='time_left_to_the_end_of_seafood'] .counter`,
        tons_of_discarded_fish: `[data-content*='tons_of_discarded_fish'] .counter`,
        tons_of_plastic_waste_dumped_in_oceans: `[data-content*='tons_of_plastic_waste_dumped_in_oceans'] .counter`,
        tons_of_plastic_waste_dumped_in_oceans: `[data-content*='tons_of_plastic_waste_dumped_in_oceans'] .counter`,
        tons_of_plastic_waste_dumped_in_oceans: `[data-content*='tons_of_plastic_waste_dumped_in_oceans'] .counter`,
        tons_of_seafood_produced: `[data-content*='tons_of_seafood_produced'] .counter`,
    },
    mining: {
        energy_use_from_mining: `[data-content*='energy_use_from_mining'] .counter`,
        energy_use_from_mining: `[data-content*='energy_use_from_mining'] .counter`,
        tons_of_coal_mined: `[data-content*='tons_of_coal_mined'] .counter`,
        tons_of_gold_mined: `[data-content*='tons_of_gold_mined'] .counter`,
        tons_of_resources_mined_from_earth: `[data-content*='tons_of_resources_mined_from_earth'] .counter`,
        tons_of_steel_produced: `[data-content*='tons_of_steel_produced'] .counter`,
        tons_of_steel_recycled: `[data-content*='tons_of_steel_recycled'] .counter`,
        tons_of_toxic_waste_produced_from_gold_mining: `[data-content*='tons_of_toxic_waste_produced_from_gold_mining'] .counter`,
        tons_of_wastewater_from_steel_mining: `[data-content*='tons_of_wastewater_from_steel_mining'] .counter`,
    },
    global_warming: {
        tons_of_co2_emitted_into_the_atmosphere: `[data-content*='tons_of_co2_emitted_into_the_atmosphere'] .counter`,
        world_average_temperature: `[data-content*='world_average_temperature'] .counter`,
        rise_in_sea_level: `[data-content*='rise_in_sea_level'] .counter`,
        tons_of_melted_ice: `[data-content*='tons_of_melted_ice'] .counter`,
    },
    freshwater: {
        deaths_from_dirty_water_and_related_diseases: `[data-content*='deaths_from_dirty_water_and_related_diseases'] .counter`,
        liters_of_water_you_have_used: `[data-content*='liters_of_water_you_have_used'] .counter`,
        number_of_people_in_need_of_water: `[data-content*='number_of_people_in_need_of_water'] .counter`,
        tons_of_virtual_water_traded: `[data-content*='tons_of_'][data-content*='virtual'][data-content*='_water_traded'] .counter`,
        tons_of_freshwater_used: `[data-content*='tons_of_freshwater_used'] .counter`,
        tons_of_freshwater_used: `[data-content*='tons_of_freshwater_used'] .counter`,
        tons_of_groundwater_being_polluted: `[data-content*='tons_of_groundwater_being_polluted'] .counter`,
        tons_of_water_used_for_our_consumption: `[data-content*='tons_of_water_used_for_our_consumption'] .counter`,
        tons_of_water_used_for_our_consumption: `[data-content*='tons_of_water_used_for_our_consumption'] .counter`,
    },
    forests: {
        cubic_meters_of_wood_produced: `[data-content*='cubic_meters_of_wood_produced'] .counter`,
        cubic_metres_of_roundwood_from_responsibly_managed_forests: `[data-content*='cubic_metres_of_roundwood_from_responsibly_managed_forests'] .counter`,
        hectares_of_forests_cut_down_or_burned: `[data-content*='hectares_of_forests_cut_down_or_burned'] .counter`,
        hectares_of_replanted_forests: `[data-content*='hectares_of_replanted_forests'] .counter`,
        percent_of_species_in_critical_risk_of_extinction: `[data-content*='percent_of_species_in_critical_risk_of_extinction'] .counter`,
        percent_of_wild_forests_left: `[data-content*='percent_of_wild_forests_left'] .counter`,
        square_kilometers_of_land_area_being_degraded: `[data-content*='square_kilometers_of_land_area_being_degraded'] .counter`,
    },

    foods: {
        aluminium_cans_consumed: `[data-content*='aluminium_cans_consumed'] .counter`,
        recycled_aluminium: `[data-content*='recycled_aluminium'] .counter`,
        tons_of_antibiotics_used_for_livestock: `[data-content*='tons_of_antibiotics_used_for_livestock'] .counter`,
        tons_of_chocolate_eaten: `[data-content*='tons_of_chocolate_eaten'] .counter`,
        tons_of_food_lost_or_wasted: `[data-content*='tons_of_food_lost_or_wasted'] .counter`,
        tons_of_meat_eaten: `[data-content*='tons_of_meat_eaten'] .counter`,
        tons_of_water_used_in_meat_production: `[data-content*='tons_of_water_used_in_meat_production'] .counter`,
        us_dollars_spent_on_organic_food: `[data-content*='us_dollars_spent_on_organic_food'] .counter`,
    },
    energy: {
        percent_of_electricity_produced_from_renewable_sources: `[data-content*='percent_of_electricity_produced_from_renewable_sources'] .counter`,
        terajoules_of_electricity_used: `[data-content*='terajoules_of_electricity_used'] .counter`,
        terajoules_of_electricity_used: `[data-content*='terajoules_of_electricity_used'] .counter`,
        terajoules_of_energy_used: `[data-content*='terajoules_of_energy_used'] .counter`,
        terajoules_of_solar_energy_striking_earth: `[data-content*='terajoules_of_solar_energy_striking_earth'] .counter`,
    },
    clothing: {
        tons_of_cotton_produced: `[data-content*='tons_of_cotton_produced'] .counter`,
        tons_of_organic_cotton_produced: `[data-content*='tons_of_organic_cotton_produced'] .counter`,
        tons_of_paper_produced: `[data-content*='tons_of_paper_produced'] .counter`,
        tons_of_water_used_in_cotton_production: `[data-content*='tons_of_water_used_in_cotton_production'] .counter`,
        us_dollars_spent_on_cotton_pesticides: `[data-content*='us_dollars_spent_on_cotton_pesticides'] .counter`,
    },
    chemicals: {
        tons_of_bisphenol_a_produced: `[data-content*='tons_of_bisphenol_a_produced'] .counter`,
        tons_of_pesticides_used: `[data-content*='tons_of_pesticides_used'] .counter`,
        tons_of_phthalates_produced: `[data-content*='tons_of_phthalates_produced'] .counter`,
        tons_of_pvc_plastics_produced: `[data-content*='tons_of_pvc_plastics_produced'] .counter`,
    },
    challenges: {
        cars_produced: `[data-content*='cars_produced'] .counter`,
    },

    air: {
        deaths_from_air_pollution: `[data-content*='deaths_from_air_pollution'] .counter`,
        deaths_from_indoor_air_pollution: `[data-content*='deaths_from_indoor_air_pollution'] .counter`,
        liters_of_air_that_you_have_inhaled: `[data-content*='liters_of_air_that_you_have_inhaled'] .counter`,
        time_left_to_recovery_of_the_ozone_hole: `[data-content*='time_left_to_recovery_of_the_ozone_hole'] .counter`,
        years_of_healthy_life_lost_from_air_pollution: `[data-content*='years_of_healthy_life_lost_from_air_pollution'] .counter`,
    },
};

export const oldselector = {
    worldometers: {
        tox_chem_this_year: `[rel="tox_chem/this_year"]`,
        soil_erosion_this_year: `[rel="soil_erosion/this_year"]`,
        desert_land_formed_this_year: `[rel="desert_land_formed/this_year"]`,
        energy_used_today: `[rel="energy_used/today"]`,
        energy_nonren: `[rel="energy_nonren"]`,
        oil_reserves: `[rel="oil_reserves"]`,
        oil_consumption: `[rel="oil_consumption"]`,
        oil_days: `[rel="oil_days"]`,
        gas_days: `[rel="gas_days"]`,
        gas_reserves: `[rel="gas_reserves"]`,
        coal_days: `[rel="coal_days"]`,
        coal_reserves: `[rel="coal_reserves"]`,
    },
    people: {
        number_of_obese_people: `[data-content*='number of obese people'] .counter`,
        people_who_died_from_hunger: `[data-content*='people who died from hunger'] .counter`,
    },
    other: {
        tons_of_paper_produced: `[data-content*='tons of paper produced'] .counter`,
        gigajoules_used_in_households: `[data-content*='gigajoules used in households'] .counter`,
    },
    clothing: {
        tons_of_cotton_produced: `[data-content*='tons of cotton produced'] .counter`,
        tons_of_organic_cotton_produced: `[data-content*='tons of organic cotton produced'] .counter`,
        us_dollars_spent_on_cotton_pesticides: `[data-content*='us dollars spent on cotton pesticides'] .counter`,
        tons_of_water_used_in_cotton_production: `[data-content*='tons of water used in cotton production'] .counter`,
    },
    foods: {
        tons_of_meat_eaten: `[data-content*='tons of meat eaten'] .counter`,
        tons_of_water_used_in_meat_production: `[data-content*='tons of water used in meat production'] .counter`,
        tons_of_antibiotics_used_for_livestock: `[data-content*='tons of antibiotics used for livestock'] .counter`,
        aluminium_cans_consumed: `[data-content*='aluminium cans consumed'] .counter`,
        recycled_aluminium_cans: `[data-content*='recycled aluminium cans'] .counter`,
        us_dollars_spent_on_organic_food: `[data-content*='us dollars spent on organic food'] .counter`,
    },
    challenges: {
        cars_produced: `[data-content*='cars produced'] .counter`,
        tons_of_food_lost_or_wasted: `[data-content*='tons of food lost or wasted'] .counter`,
    },
    planet: {
        world_population: `[data-content*='world population'] .counter`,
        tons_of_resources_extracted_from_earth: `[data-content*='tons of resources extracted from earth'] .counter`,
        tons_of_waste_dumped: `[data-content*='tons of waste dumped'] .counter`,
        earth_running_out_of_food: `[data-content*='earth running out of food'] .counter`,
        tons_of_solid_waste_generated: `[data-content*='tons of solid waste generated'] .counter`,
        time_left_till_no_more_fish_in_the_sea: `[data-content*='time left till no more fish in the sea'] .counter`,
        time_left_till_the_end_of_rainforests: `[data-content*='time left till the end of rainforests'] .counter`,
    },
    freshwater: {
        tons_of_freshwater_used: `[data-content*='tons of freshwater used'] .counter`,
        tons_of_virtual_water_traded: `[data-content*="tons of 'virtual' water traded"] .counter`,
        liters_of_water_you_have_used: `[data-content*='liters of water you have used'] .counter`,
        deaths_from_dirty_water_and_related_diseases: `[data-content*='deaths from dirty water and related diseases'] .counter`,
        number_of_people_in_need_of_water: `[data-content*='number of people in need of water'] .counter`,
        tons_of_groundwater_being_polluted: `[data-content*='tons of groundwater being polluted'] .counter`,
        tons_of_water_used_for_our_consumption: `[data-content*='tons of water used for our consumption'] .counter`,
    },
    mining: {
        tons_of_resources_mined_from_earth: `[data-content*='tons of resources mined from earth'] .counter`,
        tons_of_gold_mined: `[data-content*='tons of gold mined'] .counter`,
        tons_of_toxic_waste_produced_from_gold_mining: `[data-content*='tons of toxic waste produced from gold mining'] .counter`,
        tons_of_coal_mined: `[data-content*='tons of coal mined'] .counter`,
        tons_of_steel_recycled: `[data-content*='tons of steel recycled'] .counter`,
        tons_of_steel_produced: `[data-content*='tons of steel produced'] .counter`,
        tons_of_wastewater_from_steel_mining: `[data-content*='tons of wastewater from steel mining'] .counter`,
        energy_use_from_mining: `[data-content*='energy use from mining'] .counter`,
    },
    air: {
        tons_of_seafood_produced: `[data-content*='years of healthy life lost from air pollution'] .counter`,
        deaths_from_air_pollution: `[data-content*='deaths from air pollution'] .counter`,
        time_left_to_recovery_of_the_ozone_hole: `[data-content*='time left to recovery of the ozone hole'] .counter`,
        deaths_from_indoor_air_pollution: `[data-content*='deaths from indoor air pollution'] .counter`,
        liters_of_air_that_you_have_inhale: `[data-content*='liters of air that you have inhale'] .counter`,
    },
    oceans: {
        tons_of_seafood_produced: `[data-content*='tons of seafood produced'] .counter`,
        percent_coral_reefs_left: `[data-content*='percent coral reefs left'] .counter`,
        time_left_to_the_end_of_seafood: `[data-content*='time left to the end of seafood'] .counter`,
        tons_of_discarded_fish: `[data-content*='tons of discarded fish'] .counter`,
        tons_of_plastic_waste_dumped_in_oceans: `[data-content*='tons of plastic waste dumped in oceans'] .counter`,
    },
    forests: {
        hectares_of_forests_cut_down_or_burned: `[data-content*='hectares of forests cut down or burned'] .counter`,
        percent_of_wild_forests_left: `[data-content*='percent of wild forests left'] .counter`,
        cubic_metres_of_roundwood_from_responsibly_managed_forests: `[data-content*='cubic metres of roundwood from responsibly managed forests'] .counter`,
        hectares_of_replanted_forests: `[data-content*='hectares of replanted forests'] .counter`,
        square_kilometers_of_land_area_being_degraded: `[data-content*='square kilometers of land area being degraded'] .counter`,
        cubic_meters_of_wood_produced: `[data-content*='cubic meters of wood produced'] .counter`,
        percent_of_species_in_critical_risk_of_extinction: `[data-content*='percent of species in critical risk of extinction'] .counter`,
    },
    waste: {
        tons_of_waste_from_households: `[data-content*='tons of waste from households'] .counter`,
        tons_of_electronic_waste_thrown_out: `[data-content*='tons of electronic waste thrown out'] .counter`,
        number_of_plastic_bags_produced: `[data-content*='number of plastic bags produced'] .counter`,
        great_pacific_garbage_patch: `[data-content*='great pacific garbage patch'] .counter`,
        tons_of_hazardous_waste_thrown_out: `[data-content*='tons of hazardous waste thrown out'] .counter`,
        tons_of_waste_dumped: `[data-content*='tons of waste dumped'] .counter`,
    },
    energy: {
        terajoules_of_energy_used: `[data-content*='terajoules of energy used'] .counter`,
        percent_of_electricity_produced_from_renewable_sources: `[data-content*='percent of electricity produced from renewable sources'] .counter`,
        terajoules_of_solar_energy_striking_earth: `[data-content*='terajoules of solar energy striking earth'] .counter`,
        terajoules_of_electricity_used: `[data-content*='terajoules of electricity used'] .counter`,
        time_left_to_the_end_of_oil: `[data-content*='time left to the end of oil'] .counter`,
    },
    global_warming: {
        tons_of_co2_emitted_into_the_atmosphere: `[data-content*='tons of co2 emitted into the atmosphere'] .counter`,
        world_average_temperature: `[data-content*='world average temperature'] .counter`,
        rise_in_sea_levels: `[data-content*='rise in sea levels'] .counter`,
        tons_of_melted_ice: `[data-content*='tons of melted ice'] .counter`,
    },
    chemicals: {
        tons_of_pesticides_used: `[data-content*='tons of pesticides used'] .counter`,
        tons_of_hazardous_waste_produced: `[data-content*='tons of hazardous waste produced'] .counter`,
        tons_of_bisphenol_a_produced: `[data-content*='tons of bisphenol a produced'] .counter`,
        tons_of_pvc_plastics_produced: `[data-content*='tons of pvc plastics produced'] .counter`,
        tons_of_phthalates_produced: `[data-content*='tons of phthalates produced'] .counter`,
    },
};
